version: "3.7"
services:
  backend-dev:
    build: ../../backend
    container_name: ses-2a-backend-dev
    environment:
      - STAGE=dev
    volumes:
      - ../../backend:/app
    ports:
      - 3000:3000
